import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="min-h-screen flex flex-col">
        <header className="bg-blue-600 text-white p-4">
          <nav className="container mx-auto flex space-x-4">
            <Link href="/" className="hover:underline">Home</Link>
            <Link href="/about" className="hover:underline">About</Link>
            <Link href="/blog" className="hover:underline">Blog</Link>
            <Link href="/profile" className="hover:underline">Profile</Link>
          </nav>
        </header>
        <main className={`${geistSans.variable} ${geistMono.variable} antialiased flex-1 container mx-auto p-6`}
        >
          {children}
        </main>
        <footer className="bg-gray-100 text-center p-4">
          © {new Date().getFullYear()} My Company
        </footer>
      </body>
    </html>
  );
}
